/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package andriawan.kasir.view;

import andriawan.kasir.controller.BarangController;
import andriawan.kasir.controller.StrukController;
import andriawan.kasir.controller.TransaksiController;
import andriawan.kasir.controller.UserLoginController;
import andriawan.kasir.model.Barang;
import andriawan.kasir.model.DetailTransaksi;
import andriawan.kasir.model.ItemStruk;
import andriawan.kasir.model.Struk;
import andriawan.kasir.model.TableBarang;
import andriawan.kasir.model.TableListBelanja;
import andriawan.kasir.model.Transaksi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import utilities.ConnectionManager;
import utilities.Formater;

/**
 *
 * @author andriawan
 */
public class KasirForm extends javax.swing.JFrame {
    
    private TableBarang tb;

    /**
     * Creates new form KasirForm
     */
    public KasirForm() {
        initComponents();
        setUpIcon();
        jCheckKodeBarang.setSelected(true);
        initListTableBelanja();

    }

    public JLabel getTxtPetugasKasir() {
        return txtPetugasKasir;
    }

    public void setTxtPetugasKasir(String s) {
        this.txtPetugasKasir.setText(s);
    }

    public JLabel getTxtTotalPemasukan() {
        return txtTotalPemasukan;
    }

    public void setTxtTotalPemasukan(JLabel txtTotalPemasukan) {
        this.txtTotalPemasukan = txtTotalPemasukan;
    }

    public JLabel getTxtTotalPemasukanHariIni() {
        return txtTotalPemasukanHariIni;
    }

    public void setTxtTotalPemasukanHariIni(JLabel txtTotalPemasukanHariIni) {
        this.txtTotalPemasukanHariIni = txtTotalPemasukanHariIni;
    }

    public JLabel getTxtWaktuLogin() {
        return txtWaktuLogin;
    }

    public void setTxtWaktuLogin(String s) {
        this.txtWaktuLogin.setText(s);
    }

    public JLabel getLabelIdKasir() {
        return labelIdKasir;
    }

    public void clearRecentKasirComponents() {
        jScrollPaneKasirBarang.setViewport(null);
        DefaultTableModel listBelanja = (DefaultTableModel) jTableListBelanja.getModel();
        listBelanja.setRowCount(0);
        txtTerbilang.setText("");
        txtKembalian.setText("");
        labelTotalBig.setText("");
        labelTotalFooter.setText("");
        labelKembalian.setText("");
    }

    public void setLabelIdKasir(String s) {
        this.labelIdKasir.setText(s);
    }
    
    private void initListTableBelanja(){
        jTableListBelanja.removeColumn(
                jTableListBelanja.getColumnModel().getColumn(4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBarang = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPaneKasirBarang = new javax.swing.JScrollPane();
        jTableBarangKasir = new javax.swing.JTable();
        panelSearchBarang = new javax.swing.JPanel();
        btnCariBarang = new javax.swing.JButton();
        txtCariBarang = new javax.swing.JTextField();
        jCheckKodeBarang = new javax.swing.JCheckBox();
        jCheckNamaBarang = new javax.swing.JCheckBox();
        jLabelListBelanja = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListBelanja = new javax.swing.JTable();
        btnCetakStruk = new javax.swing.JButton();
        btnHapusItemBelanja = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelTotalFooter = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        labelKembalian = new javax.swing.JLabel();
        btnHapusListBelanja = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelBanner = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPetugasKasir = new javax.swing.JLabel();
        txtWaktuLogin = new javax.swing.JLabel();
        txtTotalPemasukan = new javax.swing.JLabel();
        txtTotalPemasukanHariIni = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelKasir = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelIdKasir = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelTotalBig = new javax.swing.JLabel();
        txtTerbilang = new javax.swing.JLabel();
        jMenuBarInfoPengembang = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        infoAplikasi = new javax.swing.JMenuItem();

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Stok"
            }
        ));
        tableBarang.setRowHeight(30);
        tableBarang.setRowMargin(5);
        jScrollBarang.setViewportView(tableBarang);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AndKasir versi 1");
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        jTableBarangKasir.setForeground(new java.awt.Color(4, 0, 0));
        jTableBarangKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableBarangKasir.setIntercellSpacing(new java.awt.Dimension(10, 5));
        jTableBarangKasir.setRowHeight(25);
        jTableBarangKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableBarangKasirMousePressed(evt);
            }
        });
        jTableBarangKasir.getTableHeader().setReorderingAllowed(false);
        jScrollPaneKasirBarang.setViewportView(jTableBarangKasir);

        btnCariBarang.setBackground(new java.awt.Color(0, 102, 255));
        btnCariBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnCariBarang.setText("Cari Barang");
        btnCariBarang.setBorderPainted(false);
        btnCariBarang.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btnCariBarang.setName(""); // NOI18N
        btnCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBarangActionPerformed(evt);
            }
        });

        txtCariBarang.setForeground(new java.awt.Color(4, 0, 0));
        txtCariBarang.setText("Masukan kode barang atau nama barang");
        txtCariBarang.setToolTipText("");
        txtCariBarang.setMargin(new java.awt.Insets(0, 5, 0, 0));
        txtCariBarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCariBarangFocusGained(evt);
            }
        });
        txtCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariBarangActionPerformed(evt);
            }
        });
        txtCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariBarangKeyPressed(evt);
            }
        });

        jCheckKodeBarang.setText("Kode Barang");

        jCheckNamaBarang.setText("Nama Barang");

        javax.swing.GroupLayout panelSearchBarangLayout = new javax.swing.GroupLayout(panelSearchBarang);
        panelSearchBarang.setLayout(panelSearchBarangLayout);
        panelSearchBarangLayout.setHorizontalGroup(
            panelSearchBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchBarangLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelSearchBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSearchBarangLayout.createSequentialGroup()
                        .addComponent(jCheckKodeBarang)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckNamaBarang)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelSearchBarangLayout.createSequentialGroup()
                        .addComponent(txtCariBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelSearchBarangLayout.setVerticalGroup(
            panelSearchBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchBarangLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelSearchBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCariBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCariBarang))
                .addGap(8, 8, 8)
                .addGroup(panelSearchBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelListBelanja.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelListBelanja.setForeground(new java.awt.Color(4, 0, 0));
        jLabelListBelanja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelListBelanja.setText("List Belanja");

        jTableListBelanja.setModel(new TableListBelanja());
        jTableListBelanja.setIntercellSpacing(new java.awt.Dimension(10, 5));
        jTableListBelanja.setNextFocusableComponent(tableBarang);
        jTableListBelanja.setRowHeight(25);
        jTableListBelanja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableListBelanjaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableListBelanjaFocusLost(evt);
            }
        });
        jTableListBelanja.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableListBelanjaPropertyChange(evt);
            }
        });
        jTableListBelanja.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableListBelanja);

        btnCetakStruk.setBackground(new java.awt.Color(0, 102, 255));
        btnCetakStruk.setForeground(new java.awt.Color(255, 255, 255));
        btnCetakStruk.setText("Cetak Struk");
        btnCetakStruk.setBorderPainted(false);
        btnCetakStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakStrukActionPerformed(evt);
            }
        });

        btnHapusItemBelanja.setBackground(new java.awt.Color(255, 0, 27));
        btnHapusItemBelanja.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusItemBelanja.setText("Hapus Item");
        btnHapusItemBelanja.setBorderPainted(false);
        btnHapusItemBelanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusItemBelanjaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(4, 0, 0));
        jLabel13.setText("Total");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(4, 0, 0));
        jLabel14.setText("Bayar");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(4, 0, 0));
        jLabel15.setText("Kembalian");

        labelTotalFooter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTotalFooter.setForeground(new java.awt.Color(4, 0, 0));
        labelTotalFooter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalFooter.setText("Rp 0");

        txtKembalian.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtKembalian.setForeground(new java.awt.Color(4, 0, 0));
        txtKembalian.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKembalian.setText("0");
        txtKembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKembalianKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKembalianKeyReleased(evt);
            }
        });

        labelKembalian.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelKembalian.setForeground(new java.awt.Color(0, 153, 51));
        labelKembalian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKembalian.setText("Rp 0");

        btnHapusListBelanja.setBackground(new java.awt.Color(255, 102, 51));
        btnHapusListBelanja.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusListBelanja.setText("Hapus List");
        btnHapusListBelanja.setBorderPainted(false);
        btnHapusListBelanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusListBelanjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSearchBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneKasirBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotalFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKembalian)
                            .addComponent(labelKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCetakStruk, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(btnHapusItemBelanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHapusListBelanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelListBelanja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSearchBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelListBelanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneKasirBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCetakStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusItemBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusListBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTotalFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(labelKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabelBanner.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelBanner.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBanner.setText(" AndKasir Desktop Versi 1");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Waktu Login");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Petugas Kasir");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Pemasukan");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Pemasukan Hari ini");

        txtPetugasKasir.setForeground(new java.awt.Color(255, 255, 255));
        txtPetugasKasir.setText("jLabel6");

        txtWaktuLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtWaktuLogin.setText("jLabel6");

        txtTotalPemasukan.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalPemasukan.setText("Rp. 0,00");

        txtTotalPemasukanHariIni.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalPemasukanHariIni.setText("Rp. 0,00");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(":");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(":");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");

        labelKasir.setForeground(new java.awt.Color(255, 255, 255));
        labelKasir.setText("ID Kasir");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");

        labelIdKasir.setForeground(new java.awt.Color(255, 255, 255));
        labelIdKasir.setText("jLabel17");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelBanner)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelKasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelIdKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel16))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPetugasKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWaktuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalPemasukanHariIni, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(172, 172, 172))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBanner)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtWaktuLogin)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKasir)
                    .addComponent(jLabel16)
                    .addComponent(labelIdKasir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPetugasKasir)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalPemasukan)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalPemasukanHariIni)
                    .addComponent(jLabel9))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Total Bayar");

        labelTotalBig.setFont(new java.awt.Font("Dialog", 1, 50)); // NOI18N
        labelTotalBig.setForeground(new java.awt.Color(255, 255, 255));
        labelTotalBig.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtTerbilang.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTerbilang.setForeground(new java.awt.Color(255, 255, 255));
        txtTerbilang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTotalBig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addComponent(txtTerbilang, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTotalBig, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTerbilang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addGap(0, 600, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jMenu1.setText("File");

        jMenuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuLogout.setText("Log Out");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLogout);

        jMenuBarInfoPengembang.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Info Pengembang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        infoAplikasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        infoAplikasi.setText("Info Aplikasi");
        infoAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoAplikasiActionPerformed(evt);
            }
        });
        jMenu2.add(infoAplikasi);

        jMenuBarInfoPengembang.add(jMenu2);

        setJMenuBar(jMenuBarInfoPengembang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBarangActionPerformed

        Barang barang = null;
        List<Barang> brList = null;

        BarangController bc = new BarangController();
        String name = txtCariBarang.getText();

        try {
            
            if(jCheckKodeBarang.isSelected()){
                brList = bc.getBarangByKode(name);
                
            }else if(jCheckNamaBarang.isSelected() && jCheckKodeBarang.isSelected() == false){
                
                barang = bc.getBarangByName(name);
                brList = new ArrayList<>();
                brList.add(barang);
                
                if (barang == null){
                    jScrollPaneKasirBarang.setViewportView(null);
                    JOptionPane.showMessageDialog(this, "Kesalahan: Data tidak ditemukan");
                }
                
            }else{
                brList = bc.multiSearch(name, name, name, name, name);                
                
                if (brList == null) {
                    
                }
            }
            
            tb = new TableBarang(brList);
            
            if (tb.getRowCount() <= 0){
                jScrollPaneKasirBarang.setViewportView(null);
                JOptionPane.showMessageDialog(this, "Kesalahan: Data tidak ditemukan");
            }
            
            jTableBarangKasir.setModel(tb);
            
            jScrollPaneKasirBarang.setViewportView(jTableBarangKasir);

        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan: Data tidak ditemukan");
        } catch (SQLException ex) {
            Logger.getLogger(KasirForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException c) {
            JOptionPane.showMessageDialog(this, "Kesalahan: Masukan hanya angka");            
        }
    }//GEN-LAST:event_btnCariBarangActionPerformed

    private void txtCariBarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariBarangFocusGained
        txtCariBarang.setText("");
    }//GEN-LAST:event_txtCariBarangFocusGained

    private void txtCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariBarangActionPerformed

    private void txtCariBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBarangKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                ActionEvent et = null;
                btnCariBarangActionPerformed(et);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtCariBarangKeyPressed

    private void jTableBarangKasirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBarangKasirMousePressed

        if (evt.getClickCount() == 2) {
            
            String id = jTableBarangKasir.getValueAt(
                    jTableBarangKasir.getSelectedRow(), 0).toString();
            String Barang = jTableBarangKasir.getValueAt(
                    jTableBarangKasir.getSelectedRow(), 2).toString();
            String hargaRp = jTableBarangKasir.getValueAt(
                    jTableBarangKasir.getSelectedRow(), 3).toString();
            int stok;
            stok = new Integer(jTableBarangKasir.getValueAt(
                    jTableBarangKasir.getSelectedRow(), 4).toString());
            
            int val = stok - 1;
            jTableBarangKasir.setValueAt(val, 
                    jTableBarangKasir.getSelectedRow(), 4);
            
            // pengecekan jika barang kosong
            if(stok <= 0){
                JOptionPane.showMessageDialog(rootPane, "Barang sedang kosong"
                        + " silahkan edit menu admin untuk melanjutkan "
                        + "transaksi");
                return;
            }

            int harga = Formater.setRupiahToInteger(hargaRp);
            int totalDefault = 1;
            ArrayList ar = new ArrayList();
            ar.add(id);
            ar.add(Barang);
            ar.add(harga);
            ar.add(totalDefault);
            ar.add(stok);
            DefaultTableModel listBelanja = (DefaultTableModel) jTableListBelanja.getModel();
            
            if (listBelanja.getRowCount() == 0) {
                listBelanja.addRow(ar.toArray());
                initTabelKasirEnv(listBelanja);
            }else{            
                for (int i = 0; i < listBelanja.getRowCount(); i++) {
                    int td = new Integer(jTableListBelanja.getValueAt(i, 3).toString());
                    String idc = jTableListBelanja.getValueAt(i, 0).toString();
                    
                    if (id.equals(idc)) {
                        if (td == stok) {
                            JOptionPane.showMessageDialog(null, "Barang pada list"
                                + " Melebih Stok");
                            return;
                        }
                        jTableListBelanja.setValueAt(totalDefault + td, i, 3);
                        initTabelKasirEnv(listBelanja);
                        return;
                    }
                }
                
                listBelanja.addRow(ar.toArray());
                initTabelKasirEnv(listBelanja);
            }
        }
    }//GEN-LAST:event_jTableBarangKasirMousePressed

    private void initTabelKasirEnv(DefaultTableModel listBelanja){
            jTableListBelanja.isCellEditable(jTableBarangKasir.getSelectedRow(), 3);
            int total = 0;

            for (int i = 0; i < listBelanja.getRowCount(); i++) {

                total = total + new Integer(
                        jTableListBelanja.getValueAt(i, 2).toString())
                        * new Integer(
                                jTableListBelanja.getValueAt(i, 3).toString());
            }

            labelTotalBig.setText(Formater.setRupiahFormat(total));
            labelTotalFooter.setText(Formater.setRupiahFormat(total));
            txtTerbilang.setText(Formater.setRupiahTerbilang(Formater.setRupiahToInteger(labelTotalBig.getText())));

            int kembalian = Formater.setRupiahToInteger(
                    txtKembalian.getText())
                    - Formater.setRupiahToInteger(labelTotalFooter.getText());

            if (kembalian < 0) {
                labelKembalian.setText("Pembayaran Tidak Mencukupi");
                labelKembalian.setForeground(Color.red);
            } else if (txtKembalian.equals("0") || txtKembalian.equals("Rp. 0,00")) {
                labelKembalian.setText("");
            } else {
                labelKembalian.setText(Formater.setRupiahFormat(kembalian));
                labelKembalian.setForeground(new Color(0, 153, 51));//Green
            }

    }
    private void txtKembalianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKembalianKeyPressed
        int raw = Formater.setRupiahToInteger(txtKembalian.getText());
        txtKembalian.setText(Integer.toString(raw));
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                int total = Formater.setRupiahToInteger(labelTotalFooter.getText());
                int bayar = new Integer(txtKembalian.getText());

                int kembalian = bayar - total;
                if (kembalian < 0) {
                    labelKembalian.setText("Pembayaran Tidak Mencukupi");
                    labelKembalian.setForeground(Color.red);
                } else if (kembalian == 0) {
                    labelKembalian.setText("Uang pas");
                    labelKembalian.setForeground(new Color(0, 153, 51));//Green
                } else {
                    labelKembalian.setText(Formater.setRupiahFormat(kembalian));
                    labelKembalian.setForeground(new Color(0, 153, 51));
                }

            }
        } catch (NumberFormatException ex) {
            txtKembalian.setText("");
        }
    }//GEN-LAST:event_txtKembalianKeyPressed

    private void txtKembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKembalianKeyReleased
        try {
            txtKembalian.setText(Formater.setRupiahFormat(Formater.setRupiahToInteger(txtKembalian.getText())));
            int total = Formater.setRupiahToInteger(labelTotalFooter.getText());
            int bayar = Formater.setRupiahToInteger(txtKembalian.getText());
            int kembalian = bayar - total;
            labelKembalian.setText(Formater.setRupiahFormat(kembalian));

            if (kembalian < 0) {
                labelKembalian.setText("Pembayaran Tidak Mencukupi");
                labelKembalian.setForeground(Color.red);
            } else if (txtKembalian.equals("0") || txtKembalian.equals("Rp. 0,00")) {
                labelKembalian.setText("");
            } else if (kembalian == 0) {
                labelKembalian.setText("Uang pas");
                labelKembalian.setForeground(new Color(0, 153, 51));//Green
            } else {
                labelKembalian.setText(Formater.setRupiahFormat(kembalian));
                labelKembalian.setForeground(new Color(0, 153, 51));//Green
            }
        } catch (Exception e) {
            txtKembalian.setText("");
            labelKembalian.setText("");
        }
    }//GEN-LAST:event_txtKembalianKeyReleased

    private void btnHapusListBelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusListBelanjaActionPerformed
        DefaultTableModel listBelanja = (DefaultTableModel) jTableListBelanja.getModel();
        listBelanja.setRowCount(0);
        labelTotalBig.setText("");
        labelTotalFooter.setText("");
        txtKembalian.setText("0");
        labelKembalian.setText("");
        txtTerbilang.setText("");
    }//GEN-LAST:event_btnHapusListBelanjaActionPerformed

    private void btnHapusItemBelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusItemBelanjaActionPerformed
        if (jTableListBelanja.getSelectedRow() >= 0) {
            DefaultTableModel listBelanja = (DefaultTableModel) jTableListBelanja.getModel();
            listBelanja.removeRow(jTableListBelanja.getSelectedRow());
            int total = 0;
            for (int i = 0; i < jTableListBelanja.getRowCount(); i++) {

                total = total + new Integer(
                        jTableListBelanja.getValueAt(i, 2).toString())
                        * new Integer(
                                jTableListBelanja.getValueAt(i, 3).toString());
            }
            int kembalian = Formater.setRupiahToInteger(txtKembalian.getText());

            int kembalianx = kembalian - total;

            labelTotalBig.setText(Formater.setRupiahFormat(total));
            labelTotalFooter.setText(Formater.setRupiahFormat(total));
            txtTerbilang.setText(Formater.setRupiahTerbilang(
                    Formater.setRupiahToInteger(labelTotalBig.getText())));

            if (kembalianx < 0) {
                labelKembalian.setText("Pembayaran Tidak Mencukupi");
                labelKembalian.setForeground(Color.red);
            } else if (kembalianx == 0) {
                labelKembalian.setText("Uang pas");
                labelKembalian.setForeground(new Color(0, 153, 51));//Green
            } else {
                labelKembalian.setText(Formater.setRupiahFormat(kembalianx));
                labelKembalian.setForeground(new Color(0, 153, 51));//Green
            }

        } else {
            JOptionPane.showMessageDialog(null, "Silahkan pilih barang yang akan dihapus dari list");
        }
    }//GEN-LAST:event_btnHapusItemBelanjaActionPerformed

    private void jTableListBelanjaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableListBelanjaFocusGained

        int jumlah, harga, total = 0, kembalian = 0;
        
         jTableListBelanja.getDefaultEditor(String.class).addCellEditorListener(
                new CellEditorListener() {
            public void editingCanceled(ChangeEvent e) {
                System.out.println("editingCanceled");
            }

            public void editingStopped(ChangeEvent e) {
                if (jTableListBelanja.getCellEditor().
                        getCellEditorValue() == null) {
                    JOptionPane.showMessageDialog(rootPane,
                            "Kesalahan: Kolom jumlah tidak boleh kosong",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    jTableListBelanja.setValueAt(
                            1,
                            jTableListBelanja.getSelectedRow(),
                            jTableListBelanja.getSelectedColumn());
                }
            }
        });
        
        try {
            
            int stok = (int) jTableListBelanja.getModel().getValueAt(
                    jTableListBelanja.getSelectedRow(), 4);

            int listStok = new Integer(
                    jTableListBelanja.getValueAt(
                            jTableListBelanja.getSelectedRow(), 3).toString());

            System.out.println("stoknya adalah: " + stok + " ,listStok :" + listStok);

            if (listStok > stok) {
                JOptionPane.showMessageDialog(null, "Barang pada list"
                        + " Melebih Stok");
                
                jTableListBelanja.setValueAt(
                    stok,
                    jTableListBelanja.getSelectedRow(),
                    jTableListBelanja.getSelectedColumn());
            }

            jumlah = new Integer(
                    jTableListBelanja.getValueAt(
                            jTableListBelanja.getSelectedRow(), 3).toString());
            harga = new Integer(
                    jTableListBelanja.getValueAt(
                            jTableListBelanja.getSelectedRow(), 2).toString());
            total = 0;
            for (int i = 0; i < jTableListBelanja.getRowCount(); i++) {
                total = total + new Integer(
                        jTableListBelanja.getValueAt(i, 2).toString())
                        * new Integer(
                                jTableListBelanja.getValueAt(i, 3).toString());
            }

            
        } catch (NumberFormatException e) {
            Logger.getLogger(ConnectionManager.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(rootPane,
                    "Kesalahan: Periksa kembali kolom jumlah pada tabel list "
                            + "belanja pastikan tidak ada yang kosong",
                    "Error", JOptionPane.ERROR_MESSAGE);
            jTableListBelanja.setValueAt(
                    1,
                    jTableListBelanja.getSelectedRow(),
                    jTableListBelanja.getSelectedColumn());
        }
        
        labelTotalBig.setText(Formater.setRupiahFormat(total));
        labelTotalFooter.setText(Formater.setRupiahFormat(total));
        txtTerbilang.setText(Formater.setRupiahTerbilang(Formater.setRupiahToInteger(labelTotalBig.getText())));

        if (txtKembalian.getText().equals("")) {
            kembalian = 0;
        }

        kembalian = Formater.setRupiahToInteger(txtKembalian.getText());
        int totalx = kembalian - total;

        if (totalx < 0) {
            labelKembalian.setText("Pembayaran Tidak Mencukupi");
            labelKembalian.setForeground(Color.red);
        } else if (totalx == 0) {
            labelKembalian.setText("Uang pas");
            labelKembalian.setForeground(new Color(0, 153, 51));//Green
        } else {
            labelKembalian.setText(Formater.setRupiahFormat(totalx));
            labelKembalian.setForeground(new Color(0, 153, 51));//Green
        }

    }//GEN-LAST:event_jTableListBelanjaFocusGained

    private void jTableListBelanjaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableListBelanjaFocusLost
       
    }//GEN-LAST:event_jTableListBelanjaFocusLost

    private void jTableListBelanjaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableListBelanjaPropertyChange
        
    }//GEN-LAST:event_jTableListBelanjaPropertyChange

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "Software AndKasir v1 ini dikembangkan oleh Muhammad Irwan Andriawan\n\n"
                + "Email andriawan2014@gmail.com\n"
                + "Telegram irwan_andriawan\n"
                + "github https://github.com/andriawan");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnCetakStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakStrukActionPerformed
        
        // mencegah aktif tombol cetak jika tidak ada pembayaran
        if("".equals(labelKembalian.getText()) || "0".equals(labelKembalian.getText())){
            JOptionPane.showMessageDialog(rootPane, "Pembayaran tidak mencukupi atau kembalian belum dihitung", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else if("".equals(txtKembalian.getText()) || "0".equals(txtKembalian.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Pembayaran tidak mencukupi atau kembalian belum dihitung", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else if(!"".equals(txtKembalian.getText())){
            int total = Formater.setRupiahToInteger(labelTotalFooter.getText());
            int bayar = Formater.setRupiahToInteger(txtKembalian.getText());
            if (bayar < total) {
                JOptionPane.showMessageDialog(rootPane, "Pembayaran tidak mencukupi atau kembalian belum dihitung", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }else {

                if (utilities.Devices.isPrinterAvailable()) {
                    
                    btnCetakStruk.setEnabled(false);

                    int harga = 0;
                    int jumlah = 0;
                    int totalHargaStruk = 0;
                    TransaksiController tc = new TransaksiController();

                    if (jTableListBelanja.getRowCount() == 0) {
                        JOptionPane.showMessageDialog(rootPane, "Silahkan tambahkan barang ke"
                                + " List belanja terlebih dahulu", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        for (int i = 0; i < jTableListBelanja.getRowCount(); i++) {
                            jumlah = jumlah + new Integer(
                                    jTableListBelanja.getValueAt(i, 3).toString());
                            harga = harga + new Integer(
                                    jTableListBelanja.getValueAt(i, 2).toString());
                            totalHargaStruk = totalHargaStruk + new Integer(
                                    jTableListBelanja.getValueAt(i, 2).toString())
                                    * new Integer(
                                            jTableListBelanja.getValueAt(i, 3).toString());
                        }
                        tc.insertTransaksi(new Transaksi(jumlah, totalHargaStruk, Calendar.getInstance().
                                getTimeInMillis(), new Integer(labelIdKasir.getText())));
                        Transaksi tr = tc.getLastRecord();
                        
                        ArrayList<ItemStruk> ais = new ArrayList<>();
                        
                        BarangController bc = new BarangController();
                        
                        for (int i = 0; i < jTableListBelanja.getRowCount(); i++) {
                            tc.insertTransaksiDetail(new DetailTransaksi(tr.getIdTransaksi(),
                                    new Integer(jTableListBelanja.getValueAt(i, 0).toString()),
                                    new Integer(jTableListBelanja.getValueAt(i, 3).toString()),
                                    new Integer(jTableListBelanja.getValueAt(i, 2).toString()),
                                    new Integer(labelIdKasir.getText())));

                            ais.add(new ItemStruk(jTableListBelanja.getValueAt(i, 1).toString(),
                                    jTableListBelanja.getValueAt(i, 3).toString(),
                                    jTableListBelanja.getValueAt(i, 2).toString(),
                                    String.valueOf(
                                            new Integer(jTableListBelanja.getValueAt(i, 2).toString())
                                            * new Integer(jTableListBelanja.getValueAt(i, 3).toString()))));

                            try {
                                bc.updateStok(
                                        new Barang(new Integer(jTableListBelanja.
                                                getValueAt(i, 0).toString())),
                                        new Integer(jTableListBelanja.
                                                getValueAt(i, 3).toString()));
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(rootPane, "Pastikan Jumlah Barang Cukup"
                            + " keadaan on", "Error", JOptionPane.ERROR_MESSAGE);
                                Logger.getLogger(KasirForm.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            
                            try {
                                bc.insertBarangKeluar(
                                        new Integer(jTableListBelanja.
                                                getValueAt(i, 0).toString()),
                                        Formater.setStringReadySql(System.currentTimeMillis()), 
                                        new Integer(jTableListBelanja.
                                                getValueAt(i, 3).toString()));
                            } catch (SQLException ex) {
                                Logger.getLogger(KasirForm.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }

                        txtTotalPemasukan.setText(utilities.Formater.setRupiahFormat(
                                utilities.Formater.setRupiahToInteger(txtTotalPemasukan.getText())
                                + utilities.Formater.setRupiahToInteger(labelTotalFooter.getText()))
                        );

                        txtTotalPemasukanHariIni.setText(utilities.Formater.setRupiahFormat(
                                utilities.Formater.setRupiahToInteger(txtTotalPemasukanHariIni.getText())
                                + utilities.Formater.setRupiahToInteger(labelTotalFooter.getText()))
                        );

                        //Cetak Struk
                        String idTransaksi = String.valueOf(tr.getIdTransaksi());
                        String idPetugas = labelIdKasir.getText();
                        String totalHarga = labelTotalFooter.getText();
                        String totalBayar = txtKembalian.getText();
                        String totalKembalian = labelKembalian.getText();
                        String tanggal = Formater.setNiceIndonesianDate(System.currentTimeMillis());
                        String namaPetugas = txtPetugasKasir.getText();

                        Struk struk = new Struk(idTransaksi, totalHarga,
                                totalBayar, totalKembalian, ais, namaPetugas, tanggal);
                        try {
                            StrukController.previewCetakStruk(struk);
                            btnCetakStruk.setEnabled(true);
                        } catch (IOException ex) {
                            Logger.getLogger(KasirForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Pastikan printer sudah dalam"
                            + " keadaan on", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        }

    }//GEN-LAST:event_btnCetakStrukActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        txtTotalPemasukan.setText("Rp. 0,00");
        dispose();
        LoginForm lf = UserLoginController.getLoginFormInstance();
        lf.setVisible(true);
        lf.setTxtFieldPengguna("");
        lf.setTxtPass("");
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void infoAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoAplikasiActionPerformed
        AboutForm af = AboutForm.getInstance();
        af.setVisible(true);
    }//GEN-LAST:event_infoAplikasiActionPerformed

    private void setUpIcon() {
        // SET ICON RESOURCE
        ImageIcon iconBtnCariBarang = new ImageIcon(
                new ImageIcon("resources/search.png").getImage().
                        getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH));
        btnCariBarang.setIcon(iconBtnCariBarang);

        ImageIcon iconBtnCetakStruk = new ImageIcon(
                new ImageIcon("resources/print.png").getImage().
                        getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH));
        btnCetakStruk.setIcon(iconBtnCetakStruk);

        ImageIcon iconHapusList = new ImageIcon(
                new ImageIcon("resources/delete.png").getImage().
                        getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH));
        btnHapusListBelanja.setIcon(iconHapusList);

        ImageIcon iconHapusItem = new ImageIcon(
                new ImageIcon("resources/delete.png").getImage().
                        getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH));
        btnHapusItemBelanja.setIcon(iconHapusItem);

        ImageIcon iconLabelListBelanja = new ImageIcon(
                new ImageIcon("resources/chart.png").getImage().
                        getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH));
        jLabelListBelanja.setIcon(iconLabelListBelanja);

        ImageIcon af = new ImageIcon(
                new ImageIcon("resources/AndKasir.png").getImage().
                        getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH));
        jLabelBanner.setIcon(af);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnCetakStruk;
    private javax.swing.JButton btnHapusItemBelanja;
    private javax.swing.JButton btnHapusListBelanja;
    private javax.swing.JMenuItem infoAplikasi;
    private javax.swing.JCheckBox jCheckKodeBarang;
    private javax.swing.JCheckBox jCheckNamaBarang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBanner;
    private javax.swing.JLabel jLabelListBelanja;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarInfoPengembang;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollBarang;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneKasirBarang;
    private javax.swing.JTable jTableBarangKasir;
    private javax.swing.JTable jTableListBelanja;
    private javax.swing.JLabel labelIdKasir;
    private javax.swing.JLabel labelKasir;
    private javax.swing.JLabel labelKembalian;
    private javax.swing.JLabel labelTotalBig;
    private javax.swing.JLabel labelTotalFooter;
    private javax.swing.JPanel panelSearchBarang;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTextField txtCariBarang;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JLabel txtPetugasKasir;
    private javax.swing.JLabel txtTerbilang;
    private javax.swing.JLabel txtTotalPemasukan;
    private javax.swing.JLabel txtTotalPemasukanHariIni;
    private javax.swing.JLabel txtWaktuLogin;
    // End of variables declaration//GEN-END:variables
}
