/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package andriawan.kasir.view;

import andriawan.kasir.controller.BarangController;
import andriawan.kasir.model.Barang;
import andriawan.kasir.model.TabelBarang;
import andriawan.kasir.model.Transaksi;
import java.awt.Dimension;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author andriawan
 */
public class MainForm extends javax.swing.JFrame{
    
    Date dt = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyy HH:mm");
    String dateF = sdf.format(dt);
    private int screenHeight;
    private int screenWidth;
    List<Barang> lb;
    List<Transaksi> tr;
   
    
    public void getSizeScreen(){
        Dimension screenSize = getMaximumSize();
        this.screenHeight = screenSize.height;
        this.screenWidth = screenSize.width;
        
    }
    

    /**
     * Creates new form MainForm
     * @throws java.sql.SQLException
     */
    public MainForm() throws SQLException {
        initComponents();
        
        BarangController bc = new BarangController();
        this.lb = bc.getAllBarang();
        
        TabelBarang tb = new TabelBarang(lb);
        tableBarang.setModel(tb);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBarang = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        panelButtonAction = new javax.swing.JPanel();
        btnCekLaporan = new javax.swing.JButton();
        btnCekBarang = new javax.swing.JButton();
        btnInfoUser = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        PanelHeader = new javax.swing.JPanel();
        txtHeader = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        panelTabel = new javax.swing.JPanel();
        jScrollTabelTransaksi = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        mainMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Stok"
            }
        ));
        tableBarang.setRowHeight(30);
        jScrollBarang.setViewportView(tableBarang);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        btnCekLaporan.setBackground(new java.awt.Color(51, 153, 255));
        btnCekLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnCekLaporan.setText("Cek Laporan");
        btnCekLaporan.setBorderPainted(false);
        btnCekLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekLaporanActionPerformed(evt);
            }
        });

        btnCekBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnCekBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnCekBarang.setText("Cek Barang");
        btnCekBarang.setBorderPainted(false);
        btnCekBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekBarangActionPerformed(evt);
            }
        });

        btnInfoUser.setBackground(new java.awt.Color(51, 153, 255));
        btnInfoUser.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoUser.setText("Cek User");
        btnInfoUser.setBorderPainted(false);
        btnInfoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoUserActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(51, 153, 255));
        btnTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setText("Cek Transaksi");
        btnTransaksi.setBorderPainted(false);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonActionLayout = new javax.swing.GroupLayout(panelButtonAction);
        panelButtonAction.setLayout(panelButtonActionLayout);
        panelButtonActionLayout.setHorizontalGroup(
            panelButtonActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCekLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCekBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInfoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelButtonActionLayout.setVerticalGroup(
            panelButtonActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonActionLayout.createSequentialGroup()
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCekLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCekBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtHeader.setText("Informasi Transaksi");

        date.setText("Informasi Waktu Login :" + dateF);

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addComponent(txtHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(190, 190, 190)
                .addComponent(date))
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date)))
        );

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal Transaksi", "Total Item", "Total Harga", "Petugas"
            }
        ));
        tabelTransaksi.setOpaque(true);
        tabelTransaksi.setRowHeight(30);
        jScrollTabelTransaksi.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addComponent(jScrollTabelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        mainMenu.add(jMenu1);

        jMenu2.setText("Edit");
        mainMenu.add(jMenu2);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(panelButtonAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelButtonAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekLaporanActionPerformed
        txtHeader.setText("Laporan");
    }//GEN-LAST:event_btnCekLaporanActionPerformed

    private void btnInfoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoUserActionPerformed
        txtHeader.setText("Informasi Pengguna");
    }//GEN-LAST:event_btnInfoUserActionPerformed

    private void btnCekBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekBarangActionPerformed
        txtHeader.setText("Informasi Stok Barang");
        jScrollTabelTransaksi.setViewportView(tableBarang);
    }//GEN-LAST:event_btnCekBarangActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        jScrollTabelTransaksi.setViewportView(tabelTransaksi);
        txtHeader.setText("Informasi Transaksi");
    }//GEN-LAST:event_btnTransaksiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JButton btnCekBarang;
    private javax.swing.JButton btnCekLaporan;
    private javax.swing.JButton btnInfoUser;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel date;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollBarang;
    private javax.swing.JScrollPane jScrollTabelTransaksi;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JPanel panelButtonAction;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTable tableBarang;
    private javax.swing.JLabel txtHeader;
    // End of variables declaration//GEN-END:variables

}
