/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package andriawan.kasir.view;

import andriawan.kasir.controller.BarangController;
import andriawan.kasir.controller.TransaksiController;
import andriawan.kasir.controller.UserController;
import andriawan.kasir.model.User;
import andriawan.kasir.model.Barang;
import andriawan.kasir.model.TableBarang;
import andriawan.kasir.model.TableDetailTransaksi;
import andriawan.kasir.model.TableUser;
import andriawan.kasir.model.TableTransaksi;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilities.Formater;

/**
 *
 * @author andriawan
 * 
 * TO DO:
 * 
 * 1. Set Draggable pada tabel, hal ini akan mengacaukan update ke databases
 * cek MainForm bagian Tabel User dan Barang
 * 
 * 2. Mengganti icon dan nama Frame
 * 
 * 3. Validasi dan filterasi input user
 * 
 * 4. ActionListener Keypressed Enter untuk Button supaya mempercepat penggunaan
 * tanpa mouse (Keyboard user)
 */
public class MainForm extends javax.swing.JFrame{
    
    Date dt = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyy HH:mm");
    String dateF = sdf.format(dt);
    private int screenHeight;
    private int screenWidth;

    /**
     * Creates new form MainForm
     * @throws java.sql.SQLException
     */
    public MainForm() throws SQLException {
        initComponents();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                setVisible(true);
            }
        });
        
        tableBarang.setDragEnabled(false);
        
        btnCekTransaksiActionPerformed(null);
        panelSearchTransaksi.setVisible(true);
        
        panelHeader.add(panelSearchBarang);
        panelSearchBarang.setVisible(false);
        
        panelHeader.add(panelSearchTransaksi);
        panelSearchTransaksi.setVisible(false);
        
        panelHeader.add(panelSearchUser);
        panelSearchUser.setVisible(false);
        
        panelButtonAction.add(panelCRUDBarangButton);
        panelCRUDBarangButton.setVisible(false);
        
        panelButtonAction.add(panelCRUDUserButton);
        panelCRUDUserButton.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBarang = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        jScrollUser = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        panelSearchBarang = new javax.swing.JPanel();
        btnCariBarang = new javax.swing.JButton();
        txtCariBarang = new javax.swing.JTextField();
        panelSearchTransaksi = new javax.swing.JPanel();
        btnCariTransaksi = new javax.swing.JButton();
        txtCariTransaksi = new javax.swing.JTextField();
        panelSearchUser = new javax.swing.JPanel();
        btnCariUser = new javax.swing.JButton();
        txtCariUser = new javax.swing.JTextField();
        jScrollPaneResultBarang = new javax.swing.JScrollPane();
        jTableResultBarang = new javax.swing.JTable();
        panelCRUDBarangButton = new javax.swing.JPanel();
        btnEditorTambahBarang = new javax.swing.JButton();
        btnEditorHapusBarang = new javax.swing.JButton();
        btnEditorEditBarang = new javax.swing.JButton();
        panelCRUDUserButton = new javax.swing.JPanel();
        btnTambahUser = new javax.swing.JButton();
        btnHapusUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        panelButtonAction = new javax.swing.JPanel();
        panelMainButton = new javax.swing.JPanel();
        btnCekTransaksi = new javax.swing.JButton();
        btnCekLaporan = new javax.swing.JButton();
        btnCekBarang = new javax.swing.JButton();
        btnInfoUser = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        panelTextHeader = new javax.swing.JPanel();
        txtHeader = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        panelTabel = new javax.swing.JPanel();
        jScrollTabelTransaksi = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        mainMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Stok"
            }
        ));
        tableBarang.setDragEnabled(false);
        tableBarang.setIntercellSpacing(new java.awt.Dimension(10, 5));
        tableBarang.setRowHeight(30);
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableBarangMousePressed(evt);
            }
        });
        jScrollBarang.setViewportView(tableBarang);

        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelUser.setIntercellSpacing(new java.awt.Dimension(10, 5));
        tabelUser.setRowHeight(30);
        tabelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelUserMousePressed(evt);
            }
        });
        jScrollUser.setViewportView(tabelUser);

        btnCariBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnCariBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnCariBarang.setText("Cari Barang");
        btnCariBarang.setBorderPainted(false);
        btnCariBarang.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btnCariBarang.setName(""); // NOI18N
        btnCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBarangActionPerformed(evt);
            }
        });

        txtCariBarang.setText("Masukan kode barang atau nama barang");
        txtCariBarang.setToolTipText("");
        txtCariBarang.setMargin(new java.awt.Insets(0, 5, 0, 0));
        txtCariBarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCariBarangFocusGained(evt);
            }
        });
        txtCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariBarangActionPerformed(evt);
            }
        });
        txtCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariBarangKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchBarangLayout = new javax.swing.GroupLayout(panelSearchBarang);
        panelSearchBarang.setLayout(panelSearchBarangLayout);
        panelSearchBarangLayout.setHorizontalGroup(
            panelSearchBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchBarangLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtCariBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCariBarang)
                .addGap(0, 0, 0))
        );
        panelSearchBarangLayout.setVerticalGroup(
            panelSearchBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchBarangLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelSearchBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCariBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCariBarang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCariTransaksi.setBackground(new java.awt.Color(51, 153, 255));
        btnCariTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnCariTransaksi.setText("Cari Transaksi");
        btnCariTransaksi.setBorderPainted(false);
        btnCariTransaksi.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btnCariTransaksi.setName(""); // NOI18N
        btnCariTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariTransaksiActionPerformed(evt);
            }
        });

        txtCariTransaksi.setText("Masukan kode transaksi atau tanggal");
        txtCariTransaksi.setToolTipText("");
        txtCariTransaksi.setMargin(new java.awt.Insets(0, 5, 0, 0));
        txtCariTransaksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCariTransaksiFocusGained(evt);
            }
        });
        txtCariTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariTransaksiActionPerformed(evt);
            }
        });
        txtCariTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariTransaksiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchTransaksiLayout = new javax.swing.GroupLayout(panelSearchTransaksi);
        panelSearchTransaksi.setLayout(panelSearchTransaksiLayout);
        panelSearchTransaksiLayout.setHorizontalGroup(
            panelSearchTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchTransaksiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtCariTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCariTransaksi)
                .addGap(0, 0, 0))
        );
        panelSearchTransaksiLayout.setVerticalGroup(
            panelSearchTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchTransaksiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelSearchTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCariTransaksi)
                    .addComponent(txtCariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCariUser.setBackground(new java.awt.Color(51, 153, 255));
        btnCariUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCariUser.setText("Cari User");
        btnCariUser.setBorderPainted(false);
        btnCariUser.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btnCariUser.setName(""); // NOI18N
        btnCariUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariUserActionPerformed(evt);
            }
        });

        txtCariUser.setText("Masukan kode user atau username atau nama");
        txtCariUser.setToolTipText("");
        txtCariUser.setMargin(new java.awt.Insets(0, 5, 0, 0));
        txtCariUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCariUserFocusGained(evt);
            }
        });
        txtCariUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariUserKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchUserLayout = new javax.swing.GroupLayout(panelSearchUser);
        panelSearchUser.setLayout(panelSearchUserLayout);
        panelSearchUserLayout.setHorizontalGroup(
            panelSearchUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchUserLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtCariUser, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCariUser)
                .addGap(0, 0, 0))
        );
        panelSearchUserLayout.setVerticalGroup(
            panelSearchUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchUserLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelSearchUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCariUser)
                    .addComponent(txtCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableResultBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableResultBarang.setIntercellSpacing(new java.awt.Dimension(10, 5));
        jTableResultBarang.setRowHeight(30);
        jScrollPaneResultBarang.setViewportView(jTableResultBarang);

        panelCRUDBarangButton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editor Barang", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnEditorTambahBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnEditorTambahBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnEditorTambahBarang.setText("Tambah Barang");
        btnEditorTambahBarang.setBorderPainted(false);
        btnEditorTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorTambahBarangActionPerformed(evt);
            }
        });

        btnEditorHapusBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnEditorHapusBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnEditorHapusBarang.setText("Hapus Barang");
        btnEditorHapusBarang.setBorderPainted(false);
        btnEditorHapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorHapusBarangActionPerformed(evt);
            }
        });

        btnEditorEditBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnEditorEditBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnEditorEditBarang.setText("Edit Barang");
        btnEditorEditBarang.setBorderPainted(false);
        btnEditorEditBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorEditBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCRUDBarangButtonLayout = new javax.swing.GroupLayout(panelCRUDBarangButton);
        panelCRUDBarangButton.setLayout(panelCRUDBarangButtonLayout);
        panelCRUDBarangButtonLayout.setHorizontalGroup(
            panelCRUDBarangButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDBarangButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCRUDBarangButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditorTambahBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditorHapusBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(btnEditorEditBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCRUDBarangButtonLayout.setVerticalGroup(
            panelCRUDBarangButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDBarangButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditorTambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditorHapusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditorEditBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCRUDUserButton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnTambahUser.setBackground(new java.awt.Color(51, 153, 255));
        btnTambahUser.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahUser.setText("Tambah Pengguna");
        btnTambahUser.setBorderPainted(false);
        btnTambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahUserActionPerformed(evt);
            }
        });

        btnHapusUser.setBackground(new java.awt.Color(51, 153, 255));
        btnHapusUser.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusUser.setText("Hapus Pengguna");
        btnHapusUser.setBorderPainted(false);
        btnHapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusUserActionPerformed(evt);
            }
        });

        btnEditUser.setBackground(new java.awt.Color(51, 153, 255));
        btnEditUser.setForeground(new java.awt.Color(255, 255, 255));
        btnEditUser.setText("Edit Pengguna");
        btnEditUser.setBorderPainted(false);
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCRUDUserButtonLayout = new javax.swing.GroupLayout(panelCRUDUserButton);
        panelCRUDUserButton.setLayout(panelCRUDUserButtonLayout);
        panelCRUDUserButtonLayout.setHorizontalGroup(
            panelCRUDUserButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCRUDUserButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCRUDUserButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(btnHapusUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCRUDUserButtonLayout.setVerticalGroup(
            panelCRUDUserButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDUserButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambahUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        panelButtonAction.setLayout(new javax.swing.BoxLayout(panelButtonAction, javax.swing.BoxLayout.PAGE_AXIS));

        btnCekTransaksi.setBackground(new java.awt.Color(51, 153, 255));
        btnCekTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnCekTransaksi.setText("Cek Transaksi");
        btnCekTransaksi.setBorderPainted(false);
        btnCekTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekTransaksiActionPerformed(evt);
            }
        });

        btnCekLaporan.setBackground(new java.awt.Color(51, 153, 255));
        btnCekLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnCekLaporan.setText("Cek Laporan");
        btnCekLaporan.setBorderPainted(false);
        btnCekLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekLaporanActionPerformed(evt);
            }
        });

        btnCekBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnCekBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnCekBarang.setText("Cek Barang");
        btnCekBarang.setBorderPainted(false);
        btnCekBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekBarangActionPerformed(evt);
            }
        });

        btnInfoUser.setBackground(new java.awt.Color(51, 153, 255));
        btnInfoUser.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoUser.setText("Cek User");
        btnInfoUser.setBorderPainted(false);
        btnInfoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainButtonLayout = new javax.swing.GroupLayout(panelMainButton);
        panelMainButton.setLayout(panelMainButtonLayout);
        panelMainButtonLayout.setHorizontalGroup(
            panelMainButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCekLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCekBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInfoUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCekTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMainButtonLayout.setVerticalGroup(
            panelMainButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainButtonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnCekTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCekLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCekBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInfoUser, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelButtonAction.add(panelMainButton);

        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.Y_AXIS));

        txtHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtHeader.setText("Informasi Transaksi");

        date.setText("Informasi Waktu Login : " + Formater.setNiceIndonesianDate(System.currentTimeMillis()));

        javax.swing.GroupLayout panelTextHeaderLayout = new javax.swing.GroupLayout(panelTextHeader);
        panelTextHeader.setLayout(panelTextHeaderLayout);
        panelTextHeaderLayout.setHorizontalGroup(
            panelTextHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextHeaderLayout.createSequentialGroup()
                .addComponent(txtHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date)
                .addContainerGap())
        );
        panelTextHeaderLayout.setVerticalGroup(
            panelTextHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTextHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeader)
                    .addComponent(date))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHeader.add(panelTextHeader);

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal Transaksi", "Total Item", "Total Harga", "Petugas"
            }
        ));
        tabelTransaksi.setIntercellSpacing(new java.awt.Dimension(10, 5));
        tabelTransaksi.setOpaque(true);
        tabelTransaksi.setRowHeight(30);
        tabelTransaksi.getTableHeader().setReorderingAllowed(false);
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelTransaksiMousePressed(evt);
            }
        });
        jScrollTabelTransaksi.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollTabelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        mainMenu.add(jMenu1);

        jMenu2.setText("Edit");
        mainMenu.add(jMenu2);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelButtonAction, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelButtonAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekLaporanActionPerformed
        txtHeader.setText("Laporan");
    }//GEN-LAST:event_btnCekLaporanActionPerformed

    private void btnInfoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoUserActionPerformed
        UserController uc = new UserController();
        try {
            TableUser tu = new TableUser(uc.getAllUser());
            tabelUser.setModel(tu);
            jScrollTabelTransaksi.setViewportView(tabelUser);

            txtHeader.setText("Informasi Pengguna");
            panelSearchUser.setVisible(true);
            panelSearchBarang.setVisible(false);
            panelSearchTransaksi.setVisible(false);

            panelCRUDBarangButton.setVisible(false);
            panelCRUDUserButton.setVisible(true);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnInfoUserActionPerformed

    private void btnCekBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekBarangActionPerformed
        // Set Tabel Model for Barang
        BarangController bc = new BarangController();      
        TableBarang tb;
        try {
            tb = new TableBarang(bc.getAllBarang());
            txtHeader.setText("Informasi Stok Barang");
            jScrollTabelTransaksi.setViewportView(tableBarang);
            tableBarang.setModel(tb);
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        panelSearchBarang.setVisible(true);
        panelSearchUser.setVisible(false);
        panelSearchTransaksi.setVisible(false);
        
        panelCRUDBarangButton.setVisible(true);
        panelCRUDUserButton.setVisible(false);
    }//GEN-LAST:event_btnCekBarangActionPerformed

    private void btnCekTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekTransaksiActionPerformed
        TransaksiController tc = new TransaksiController();
        TableTransaksi tt;
        
        tt = new TableTransaksi(tc.getAllTransakasi());
        txtHeader.setText("Informasi Transaksi");
        jScrollTabelTransaksi.setViewportView(tabelTransaksi);
        tabelTransaksi.setModel(tt);
                    
        txtHeader.setText("Informasi Transaksi");
        panelSearchTransaksi.setVisible(true);
        panelSearchBarang.setVisible(false);
        panelSearchUser.setVisible(false);
        
        panelCRUDBarangButton.setVisible(false);
        panelCRUDUserButton.setVisible(false);
    }//GEN-LAST:event_btnCekTransaksiActionPerformed

    private void txtCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariBarangActionPerformed

    private void txtCariTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariTransaksiActionPerformed

    private void txtCariBarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariBarangFocusGained
        txtCariBarang.setText("");
    }//GEN-LAST:event_txtCariBarangFocusGained

    private void txtCariTransaksiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariTransaksiFocusGained
        txtCariTransaksi.setText("");
    }//GEN-LAST:event_txtCariTransaksiFocusGained

    private void txtCariUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariUserFocusGained
        txtCariUser.setText("");
    }//GEN-LAST:event_txtCariUserFocusGained

    private void btnCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBarangActionPerformed
        
        try {
            BarangController bc = new BarangController();
            String name = txtCariBarang.getText();
            
            Barang barang;
            List<Barang> brList = bc.multiSearch(name, name, name, name);
            
            TableBarang tb = new TableBarang(brList);
            tableBarang.setModel(tb);
            
            jScrollTabelTransaksi.setViewportView(tableBarang);
            
        } catch (SQLException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Kesalahan: Data tidak ditemukan");
        }
    }//GEN-LAST:event_btnCariBarangActionPerformed

    private void btnTambahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahUserActionPerformed
        UserController.getInsertFormInstance().setVisible(true);
        UserController.getInsertFormInstance().
                setVisibilityBtnTambah(true);
        UserController.getInsertFormInstance().
                setVisibilityBtnUpdate(false);
        UserController.getInsertFormInstance().
                setVisibilityCombo(false);
        UserController.getInsertFormInstance().
                setEnablePassField(true);
        UserController.getInsertFormInstance().
                setLabelHeader("Tambah Pengguna");
    }//GEN-LAST:event_btnTambahUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        if(tabelUser.getSelectedRow()>= 0){
            UserController uc = new UserController();
            String s;
            s = tabelUser.getValueAt(tabelUser.getSelectedRow(), 0).toString();
            User usr = uc.getUser(new Integer(s));
            UserController.getUpdateFormInstance().
                    setVisible(true);
            UserController.getUpdateFormInstance().
                    setVisibilityBtnUpdate(true);
            UserController.getUpdateFormInstance().
                    setVisibilityBtnTambah(false);
            UserController.getUpdateFormInstance().
                    setTxtUsername(usr.getUsername());
            UserController.getUpdateFormInstance().
                    setTxtNama(usr.getNama());
            UserController.getUpdateFormInstance().
                    setTxtId(new Integer(usr.getId()).toString());
            UserController.getUpdateFormInstance().
                setLabelHeader("Edit Pengguna");
            
        }else {
            JOptionPane.showMessageDialog(null, "Pilih barang yang akan di edit pada tabel terlebih dahulu");
        }
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnEditorEditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorEditBarangActionPerformed
        if(tableBarang.getSelectedRow()>= 0){
            BarangController bc = new BarangController();
            String s;
            s = tableBarang.getValueAt(tableBarang.getSelectedRow(), 0).toString();
            try {
                Barang br = bc.getBarang(new Integer(s));
                BarangController.getUpdateFormInstance().
                        setVisible(true);
                BarangController.getUpdateFormInstance().
                        setVisibilityBtnUpdate();
                BarangController.getUpdateFormInstance().
                        setTxtFieldNamaBarang(br.getNamaBarang());
                BarangController.getUpdateFormInstance().
                        setTxtFieldHarga(Formater.setRupiahFormat(br.getHarga()));
                BarangController.getUpdateFormInstance().
                        setTxtFieldStok(String.valueOf(br.getStok()));
                BarangController.getUpdateFormInstance().
                        setTxtFieldIdBarang(String.valueOf(s));
            } catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih barang yang akan di edit pada tabel terlebih dahulu");
        }
        
    }//GEN-LAST:event_btnEditorEditBarangActionPerformed

    private void txtCariBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBarangKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                ActionEvent et = null;
                btnCariBarangActionPerformed(et);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtCariBarangKeyPressed

    private void btnEditorTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorTambahBarangActionPerformed
        BarangController.getInsertFormInstance().setVisible(true);
        BarangController.getInsertFormInstance().setVisibilityBtnTambah();
    }//GEN-LAST:event_btnEditorTambahBarangActionPerformed

    private void btnEditorHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorHapusBarangActionPerformed
        if(tableBarang.getSelectedRow()>= 0){
            BarangController bc = new BarangController();
            String id = tableBarang.getValueAt(tableBarang.getSelectedRow(), 0).toString();
            String nama = tableBarang.getValueAt(tableBarang.getSelectedRow(), 1).toString();
            String harga = tableBarang.getValueAt(tableBarang.getSelectedRow(), 2).toString();
            String stok = tableBarang.getValueAt(tableBarang.getSelectedRow(), 3).toString();
            String message = "Apakah anda yakin akan menghapus barang\n\n " 
                    + nama + " dengan harga \n"
                    + harga + " dan jumlah stok "
                    + stok + " ?";
            try {
                int action = JOptionPane.showConfirmDialog(
                        null, message, 
                        "Konfirmasi", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.INFORMATION_MESSAGE);
                if(action == JOptionPane.YES_OPTION){
                    bc.hapusBarang(new Integer(id));
                    try {
                        
                        List<Barang> brList = bc.getAllBarang();

                        TableBarang tb = new TableBarang(brList);
                        tableBarang.setModel(tb);

                        jScrollTabelTransaksi.setViewportView(tableBarang);

                    } catch (SQLException | NullPointerException ex) {
                        JOptionPane.showMessageDialog(null, "Kesalahan: Data tidak ditemukan");
                    }
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih barang yang akan di edit pada tabel terlebih dahulu");
        }
    }//GEN-LAST:event_btnEditorHapusBarangActionPerformed

    private void btnHapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusUserActionPerformed
        if (tabelUser.getSelectedRow()>= 0){
            UserController uc = new UserController();
            
            String id = tabelUser.getValueAt(tabelUser.getSelectedRow(), 0).toString();
            String username = tabelUser.getValueAt(tabelUser.getSelectedRow(), 1).toString();
            String nama = tabelUser.getValueAt(tabelUser.getSelectedRow(), 3).toString();
            String jabatan = tabelUser.getValueAt(tabelUser.getSelectedRow(), 4).toString();
            
            String message = "<html>Apakah anda yakin akan menghapus pengguna dengan \n\n username " 
                    + username + "\nNama  "
                    + nama + "\ndan jabatan "
                    + jabatan + " ?</html>";
            
            try {
                int action = JOptionPane.showConfirmDialog(
                        null, message, 
                        "Konfirmasi", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.INFORMATION_MESSAGE);
                if(action == JOptionPane.YES_OPTION){
                    uc.deleteUser(new Integer(id));
                }
                
            } catch (RuntimeException f){
                f.printStackTrace();
            }            
        }else{
            JOptionPane.showMessageDialog(
                    null, "Pilih Pengguna yang akan di hapus");
        }
    }//GEN-LAST:event_btnHapusUserActionPerformed

    private void btnCariTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTransaksiActionPerformed
        TransaksiController tc = TransaksiController.getInstanceTransaksiController();
        TableTransaksi tt = new TableTransaksi(
                tc.getTransakasi(
                        new Integer(txtCariTransaksi.getText().toString())));
        tabelTransaksi.setModel(tt);
        jScrollTabelTransaksi.setViewportView(tabelTransaksi);
    }//GEN-LAST:event_btnCariTransaksiActionPerformed

    private void btnCariUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariUserActionPerformed
        String usr = txtCariUser.getText();
        UserController uc = new UserController();        
        TableUser tu = new TableUser(
                uc.multiSeacrh(usr, usr, usr, usr));
        tabelUser.setModel(tu);
        
        jScrollTabelTransaksi.setViewportView(tabelUser);
        
    }//GEN-LAST:event_btnCariUserActionPerformed

    private void txtCariUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariUserKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                ActionEvent et = null;
                btnCariUserActionPerformed(et);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtCariUserKeyPressed

    private void txtCariTransaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariTransaksiKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                ActionEvent et = null;
                btnCariTransaksiActionPerformed(et);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtCariTransaksiKeyPressed

    private void tabelTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMousePressed
        // Jika Konten Tabel diklik 2 kali akan mengeksekusi
        // kode di bawah ini
        if(evt.getClickCount() == 2){
            int idTransaksi = new Integer(tabelTransaksi.getValueAt(
                    tabelTransaksi.getSelectedRow(), 0 ).toString());
            TransaksiController tc = new TransaksiController();
            TableDetailTransaksi tdt = new TableDetailTransaksi(tc.getDetailTransakasi(idTransaksi));
            String id = tabelTransaksi.getValueAt(
                            tabelTransaksi.getSelectedRow(), 0).toString();
            String tgl = tabelTransaksi.getValueAt(
                            tabelTransaksi.getSelectedRow(), 1).toString();
            InfoDetailTransaksiForm ifD = new InfoDetailTransaksiForm(tdt,id,tgl);
            ifD.setVisible(true);

        }
    }//GEN-LAST:event_tabelTransaksiMousePressed

    private void tabelUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUserMousePressed
        
        if(evt.getClickCount() == 2){
            btnEditUserActionPerformed(null);
            UserController.getUpdateFormInstance().
                setLabelHeader("Edit Pengguna");
        }
    }//GEN-LAST:event_tabelUserMousePressed

    private void tableBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMousePressed
        
        if(evt.getClickCount() == 2){
            btnEditorEditBarangActionPerformed(null);
        }
    }//GEN-LAST:event_tableBarangMousePressed
    // Custom Code
    public void getSizeScreen(){
        Dimension screenSize = getMaximumSize();
        this.screenHeight = screenSize.height;
        this.screenWidth = screenSize.width;
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnCariTransaksi;
    private javax.swing.JButton btnCariUser;
    private javax.swing.JButton btnCekBarang;
    private javax.swing.JButton btnCekLaporan;
    private javax.swing.JButton btnCekTransaksi;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnEditorEditBarang;
    private javax.swing.JButton btnEditorHapusBarang;
    private javax.swing.JButton btnEditorTambahBarang;
    private javax.swing.JButton btnHapusUser;
    private javax.swing.JButton btnInfoUser;
    private javax.swing.JButton btnTambahUser;
    private javax.swing.JLabel date;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollBarang;
    private javax.swing.JScrollPane jScrollPaneResultBarang;
    private javax.swing.JScrollPane jScrollTabelTransaksi;
    private javax.swing.JScrollPane jScrollUser;
    private javax.swing.JTable jTableResultBarang;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JPanel panelButtonAction;
    private javax.swing.JPanel panelCRUDBarangButton;
    private javax.swing.JPanel panelCRUDUserButton;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMainButton;
    private javax.swing.JPanel panelSearchBarang;
    private javax.swing.JPanel panelSearchTransaksi;
    private javax.swing.JPanel panelSearchUser;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JPanel panelTextHeader;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTable tabelUser;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTextField txtCariBarang;
    private javax.swing.JTextField txtCariTransaksi;
    private javax.swing.JTextField txtCariUser;
    private javax.swing.JLabel txtHeader;
    // End of variables declaration//GEN-END:variables

}
